-- =============================================================================
-- Spark Retail Pack — Privilege Grants
-- Section 2.5 | PHASE_0_CHECKLIST §0.2
--
-- Run AFTER 01, 02, 03 (databases, warehouses, and roles must exist first).
-- FUTURE grants ensure new tables/views/schemas inherit the right permissions
-- automatically — no re-running grants after each dbt run.
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- =============================================================================
-- RETAIL_LOADER — write to RAW_RETAIL only
-- =============================================================================

GRANT USAGE ON WAREHOUSE WH_LOAD TO ROLE RETAIL_LOADER;

GRANT USAGE ON DATABASE RAW_RETAIL TO ROLE RETAIL_LOADER;
GRANT CREATE SCHEMA ON DATABASE RAW_RETAIL TO ROLE RETAIL_LOADER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_RETAIL TO ROLE RETAIL_LOADER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW_RETAIL TO ROLE RETAIL_LOADER;

-- Full write so ingestion tools can create/replace/truncate tables
GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE,
      CREATE STREAM, CREATE TASK
      ON ALL SCHEMAS IN DATABASE RAW_RETAIL TO ROLE RETAIL_LOADER;
GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE,
      CREATE STREAM, CREATE TASK
      ON FUTURE SCHEMAS IN DATABASE RAW_RETAIL TO ROLE RETAIL_LOADER;

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE RAW_RETAIL TO ROLE RETAIL_LOADER;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE RAW_RETAIL TO ROLE RETAIL_LOADER;

-- =============================================================================
-- RETAIL_TRANSFORMER — read bronze, full write on all analytics databases
-- =============================================================================

GRANT USAGE ON WAREHOUSE WH_TRANSFORM TO ROLE RETAIL_TRANSFORMER;

-- Read access to bronze
GRANT USAGE ON DATABASE RAW_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT SELECT ON ALL VIEWS IN DATABASE RAW_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN DATABASE RAW_RETAIL TO ROLE RETAIL_TRANSFORMER;

-- Full write on ANALYTICS_RETAIL (production)
GRANT USAGE, CREATE SCHEMA ON DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE SEQUENCE,
      CREATE STREAM, CREATE TASK, CREATE DYNAMIC TABLE
      ON ALL SCHEMAS IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE SEQUENCE,
      CREATE STREAM, CREATE TASK, CREATE DYNAMIC TABLE
      ON FUTURE SCHEMAS IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_TRANSFORMER;

-- Full write on ANALYTICS_RETAIL_STAGING
GRANT USAGE, CREATE SCHEMA ON DATABASE ANALYTICS_RETAIL_STAGING TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_RETAIL_STAGING TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ANALYTICS_RETAIL_STAGING TO ROLE RETAIL_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE SEQUENCE,
      CREATE STREAM, CREATE TASK, CREATE DYNAMIC TABLE
      ON ALL SCHEMAS IN DATABASE ANALYTICS_RETAIL_STAGING TO ROLE RETAIL_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE SEQUENCE,
      CREATE STREAM, CREATE TASK, CREATE DYNAMIC TABLE
      ON FUTURE SCHEMAS IN DATABASE ANALYTICS_RETAIL_STAGING TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ANALYTICS_RETAIL_STAGING TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ANALYTICS_RETAIL_STAGING TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE ANALYTICS_RETAIL_STAGING TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE ANALYTICS_RETAIL_STAGING TO ROLE RETAIL_TRANSFORMER;

-- Full write on ANALYTICS_RETAIL_DEV
GRANT USAGE, CREATE SCHEMA ON DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE SEQUENCE,
      CREATE STREAM, CREATE TASK, CREATE DYNAMIC TABLE
      ON ALL SCHEMAS IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE SEQUENCE,
      CREATE STREAM, CREATE TASK, CREATE DYNAMIC TABLE
      ON FUTURE SCHEMAS IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_TRANSFORMER;

-- =============================================================================
-- RETAIL_BI_READER — read mart and semantic schemas in production only
-- Section 2.5: "Read-only on ANALYTICS_RETAIL.MART_* and ANALYTICS_RETAIL.SEMANTIC"
-- =============================================================================

GRANT USAGE ON WAREHOUSE WH_BI TO ROLE RETAIL_BI_READER;

GRANT USAGE ON DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_BI_READER;

GRANT USAGE ON SCHEMA ANALYTICS_RETAIL.MART_SALES     TO ROLE RETAIL_BI_READER;
GRANT USAGE ON SCHEMA ANALYTICS_RETAIL.MART_CUSTOMER  TO ROLE RETAIL_BI_READER;
GRANT USAGE ON SCHEMA ANALYTICS_RETAIL.MART_INVENTORY TO ROLE RETAIL_BI_READER;
GRANT USAGE ON SCHEMA ANALYTICS_RETAIL.SEMANTIC       TO ROLE RETAIL_BI_READER;

GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_RETAIL.MART_SALES     TO ROLE RETAIL_BI_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_RETAIL.MART_CUSTOMER  TO ROLE RETAIL_BI_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_RETAIL.MART_INVENTORY TO ROLE RETAIL_BI_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS_RETAIL.SEMANTIC       TO ROLE RETAIL_BI_READER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA ANALYTICS_RETAIL.MART_SALES     TO ROLE RETAIL_BI_READER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA ANALYTICS_RETAIL.MART_CUSTOMER  TO ROLE RETAIL_BI_READER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA ANALYTICS_RETAIL.MART_INVENTORY TO ROLE RETAIL_BI_READER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA ANALYTICS_RETAIL.SEMANTIC       TO ROLE RETAIL_BI_READER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_RETAIL.MART_SALES     TO ROLE RETAIL_BI_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_RETAIL.MART_CUSTOMER  TO ROLE RETAIL_BI_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_RETAIL.MART_INVENTORY TO ROLE RETAIL_BI_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS_RETAIL.SEMANTIC       TO ROLE RETAIL_BI_READER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA ANALYTICS_RETAIL.MART_SALES     TO ROLE RETAIL_BI_READER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA ANALYTICS_RETAIL.MART_CUSTOMER  TO ROLE RETAIL_BI_READER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA ANALYTICS_RETAIL.MART_INVENTORY TO ROLE RETAIL_BI_READER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA ANALYTICS_RETAIL.SEMANTIC       TO ROLE RETAIL_BI_READER;

-- =============================================================================
-- RETAIL_ANALYST — read all analytics schemas; no write
-- =============================================================================

GRANT USAGE ON WAREHOUSE WH_ADHOC TO ROLE RETAIL_ANALYST;

GRANT USAGE ON DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_ANALYST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_ANALYST;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_ANALYST;
GRANT SELECT ON ALL VIEWS IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN DATABASE ANALYTICS_RETAIL TO ROLE RETAIL_ANALYST;

-- Analysts can also read dev for debugging
GRANT USAGE ON DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_ANALYST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_ANALYST;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_ANALYST;
GRANT SELECT ON ALL VIEWS IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN DATABASE ANALYTICS_RETAIL_DEV TO ROLE RETAIL_ANALYST;

-- =============================================================================
-- RETAIL_PII_VIEWER — additive; grants on specific PII-clear views
-- The actual views don't exist yet (built in Phase 1/2).
-- This block is a placeholder — re-run after views are created.
-- Section 8.6 specifies which views fall under this role.
-- =============================================================================

-- GRANT SELECT ON VIEW ANALYTICS_RETAIL.MART_CUSTOMER.customer_pii_unmasked
--     TO ROLE RETAIL_PII_VIEWER;
-- (Uncomment and extend in Phase 2 when the view exists.)

-- =============================================================================
-- RETAIL_FINANCE_VIEWER — additive; grants on confidential-tagged columns
-- Snowflake Standard edition does not support column-level grants natively.
-- Access is controlled via dedicated mart views that expose cost/margin columns.
-- The view grants will be added here in Phase 2.
-- =============================================================================

-- GRANT SELECT ON VIEW ANALYTICS_RETAIL.MART_SALES.sales_with_margin
--     TO ROLE RETAIL_FINANCE_VIEWER;
-- (Uncomment and extend in Phase 2 when views exist.)

-- =============================================================================
-- RETAIL_ADMIN — all privileges on Retail Pack objects (humans only)
-- RETAIL_ADMIN does NOT inherit SYSADMIN (circular grant — see 03_roles.sql).
-- Explicit grants below give full control over the pack's databases and
-- warehouses. For account-level ops (new warehouses, etc.) use ACCOUNTADMIN.
-- =============================================================================

GRANT ALL PRIVILEGES ON DATABASE RAW_RETAIL             TO ROLE RETAIL_ADMIN;
GRANT ALL PRIVILEGES ON DATABASE ANALYTICS_RETAIL       TO ROLE RETAIL_ADMIN;
GRANT ALL PRIVILEGES ON DATABASE ANALYTICS_RETAIL_STAGING TO ROLE RETAIL_ADMIN;
GRANT ALL PRIVILEGES ON DATABASE ANALYTICS_RETAIL_DEV   TO ROLE RETAIL_ADMIN;

GRANT ALL PRIVILEGES ON WAREHOUSE WH_LOAD      TO ROLE RETAIL_ADMIN;
GRANT ALL PRIVILEGES ON WAREHOUSE WH_TRANSFORM TO ROLE RETAIL_ADMIN;
GRANT ALL PRIVILEGES ON WAREHOUSE WH_BI        TO ROLE RETAIL_ADMIN;
GRANT ALL PRIVILEGES ON WAREHOUSE WH_ADHOC     TO ROLE RETAIL_ADMIN;
